(wip) draft `market` module
nftlabs/nftlabs-sdk-python pull request #1
Opened 2021-10-19 18:59 UTC by atbe

2021-10-21 22:41 UTC, atbe commented on nftlabs/modules/market.py
> +            asset = NFT(from_address, arg.asset_contract)
yes, thats right @jakeloo

2021-10-21 22:43 UTC, atbe commented on nftlabs/modules/market.py
> +        result = self.__abi_module.get_new_listing_event(tx_hash=receipt.transactionHash.hex())
The `list` method should return a new listing object. We don't have a class for that yet, but it should match [this](https://github.com/nftlabs/nftlabs-sdk-ts/blob/a1e768d9ca05bfd4e22a3eb8e84a085aedb8a04f/src/market/index.ts#L25).

Be sure to annotate the `list` function with a return type like this:

```python
    def list(self, arg: ListArg) -> Listing:
```

2021-10-21 22:44 UTC, atbe commented on nftlabs/modules/market.py
> +            allowance = erc20.allowance(owner, spender)
@jakeloo  I wonder if we should be subtracting the current `allowance` when calling `increase_allowance`?

2021-10-24 01:12 UTC, jakeloo requested changes

2021-10-24 01:12 UTC, jakeloo commented on nftlabs/modules/market.py
> +            asset = NFTNFT(client, arg.asset_contract)
I think this is a typo right `NFTNFT`?

2021-10-24 01:20 UTC, jakeloo commented on nftlabs/modules/market.py
> +            asset = ERC1155(from_address, arg.asset_contract)
`from_address` -> `client`.

2021-10-25 07:22 UTC, merged